export const spanishSpeakingCountriesMenu: {
  country: string;
  labelCountry: string;
  adminType1: string;
  adminType2: string;
  children: { name: string; children?: { name: string }[] }[];
}[] = [
  {
    country: "MX",
    labelCountry: "México",
    adminType1: "estado",
    adminType2: "municipio",
    children: [
      { name: "Aguascalientes", children: [{ name: "Aguascalientes" }, { name: "Asientos" }, { name: "Calvillo" }, { name: "Cosío" }, { name: "Jesús María" }, { name: "Pabellón de Arteaga" }, { name: "Rincón de Romos" }, { name: "San José de Gracia" }, { name: "Tepezalá" }, { name: "El Llano" }, { name: "San Francisco de los Romo" }] },
      { name: "Baja California", children: [{ name: "Ensenada" }, { name: "Mexicali" }, { name: "Tecate" }, { name: "Tijuana" }, { name: "Playas de Rosarito" }, { name: "San Quintín" }, { name: "San Felipe" }] },
      { name: "Baja California Sur", children: [{ name: "Comondú" }, { name: "Mulegé" }, { name: "La Paz" }, { name: "Los Cabos" }, { name: "Loreto" }] },
      { name: "Campeche", children: [{ name: "Calkiní" }, { name: "Campeche" }, { name: "Carmen" }, { name: "Champotón" }, { name: "Hecelchakán" }, { name: "Hopelchén" }, { name: "Palizada" }, { name: "Tenabo" }, { name: "Escárcega" }, { name: "Calakmul" }, { name: "Candelaria" }, { name: "Seybaplaya" }, { name: "Dzitbalché" }] },
      { name: "Chiapas", children: [{ name: "Tuxtla Gutiérrez" }, { name: "San Cristóbal de las Casas" }, { name: "Tapachula" }, { name: "Palenque" }, { name: "Comitán de Domínguez" }, { name: "Chiapa de Corzo" }, { name: "Ocosingo" }, { name: "Tonalá" }, { name: "Villaflores" }, { name: "Cintalapa" }, { name: "Berriozábal" }, { name: "Arriaga" }] },
      { name: "Chihuahua", children: [{ name: "Chihuahua" }, { name: "Juárez" }, { name: "Cuauhtémoc" }, { name: "Delicias" }, { name: "Hidalgo del Parral" }, { name: "Nuevo Casas Grandes" }, { name: "Camargo" }, { name: "Jiménez" }, { name: "Ojinaga" }, { name: "Meoqui" }, { name: "Aldama" }, { name: "Guachochi" }] },
      { name: "Ciudad de México", children: [{ name: "Álvaro Obregón" }, { name: "Azcapotzalco" }, { name: "Benito Juárez" }, { name: "Coyoacán" }, { name: "Cuajimalpa de Morelos" }, { name: "Cuauhtémoc" }, { name: "Gustavo A. Madero" }, { name: "Iztacalco" }, { name: "Iztapalapa" }, { name: "La Magdalena Contreras" }, { name: "Miguel Hidalgo" }, { name: "Milpa Alta" }, { name: "Tláhuac" }, { name: "Tlalpan" }, { name: "Venustiano Carranza" }, { name: "Xochimilco" }] },
      { name: "Coahuila", children: [{ name: "Saltillo" }, { name: "Torreón" }, { name: "Monclova" }, { name: "Piedras Negras" }, { name: "Acuña" }, { name: "Matamoros" }, { name: "San Pedro" }, { name: "Frontera" }, { name: "Múzquiz" }, { name: "Sabinas" }, { name: "Ramos Arizpe" }, { name: "Parras" }] },
      { name: "Colima", children: [{ name: "Armería" }, { name: "Colima" }, { name: "Comala" }, { name: "Coquimatlán" }, { name: "Cuauhtémoc" }, { name: "Ixtlahuacán" }, { name: "Manzanillo" }, { name: "Minatitlán" }, { name: "Tecomán" }, { name: "Villa de Álvarez" }] },
      { name: "Durango", children: [{ name: "Durango" }, { name: "Gómez Palacio" }, { name: "Lerdo" }, { name: "Pueblo Nuevo" }, { name: "Santiago Papasquiaro" }, { name: "Guadalupe Victoria" }, { name: "San Juan del Río" }, { name: "Tamazula" }, { name: "Canatlán" }, { name: "Nuevo Ideal" }] },
      { name: "Guanajuato", children: [{ name: "León" }, { name: "Irapuato" }, { name: "Celaya" }, { name: "Salamanca" }, { name: "Silao de la Victoria" }, { name: "Guanajuato" }, { name: "San Miguel de Allende" }, { name: "Dolores Hidalgo" }, { name: "Valle de Santiago" }, { name: "San Francisco del Rincón" }, { name: "Cortazar" }, { name: "Acámbaro" }, { name: "Pénjamo" }] },
      { name: "Guerrero", children: [{ name: "Acapulco de Juárez" }, { name: "Chilpancingo de los Bravo" }, { name: "Iguala de la Independencia" }, { name: "Zihuatanejo de Azueta" }, { name: "Taxco de Alarcón" }, { name: "Chilapa de Álvarez" }, { name: "Tlapa de Comonfort" }, { name: "Zumpango del Río" }, { name: "Petatlán" }, { name: "Ometepec" }, { name: "Tixtla de Guerrero" }] },
      { name: "Hidalgo", children: [{ name: "Pachuca de Soto" }, { name: "Tulancingo de Bravo" }, { name: "Mineral de la Reforma" }, { name: "Tizayuca" }, { name: "Huejutla de Reyes" }, { name: "Tepeji del Río de Ocampo" }, { name: "Tula de Allende" }, { name: "Ixmiquilpan" }, { name: "Tepeapulco" }, { name: "Actopan" }, { name: "Zimapán" }] },
      { name: "Jalisco", children: [{ name: "Guadalajara" }, { name: "Zapopan" }, { name: "San Pedro Tlaquepaque" }, { name: "Tlajomulco de Zúñiga" }, { name: "Tonalá" }, { name: "Puerto Vallarta" }, { name: "Lagos de Moreno" }, { name: "Tepatitlán de Morelos" }, { name: "Zapotlán el Grande" }, { name: "Ocotlán" }, { name: "Arandas" }, { name: "Ameca" }, { name: "Atotonilco el Alto" }, { name: "Autlán de Navarro" }, { name: "Tala" }] },
      { name: "México", children: [{ name: "Ecatepec de Morelos" }, { name: "Nezahualcóyotl" }, { name: "Toluca" }, { name: "Naucalpan de Juárez" }, { name: "Chimalhuacán" }, { name: "Tlalnepantla de Baz" }, { name: "Cuautitlán Izcalli" }, { name: "Tecámac" }, { name: "Ixtapaluca" }, { name: "Atizapán de Zaragoza" }, { name: "Tultitlán" }, { name: "Valle de Chalco Solidaridad" }, { name: "Nicolás Romero" }, { name: "Chalco" }, { name: "Coacalco de Berriozábal" }, { name: "La Paz" }, { name: "Huixquilucan" }, { name: "Texcoco" }, { name: "Metepec" }] },
      { name: "Michoacán", children: [{ name: "Morelia" }, { name: "Uruapan" }, { name: "Zamora" }, { name: "Lázaro Cárdenas" }, { name: "Zitácuaro" }, { name: "Apatzingán" }, { name: "Hidalgo" }, { name: "La Piedad" }, { name: "Tarímbaro" }, { name: "Pátzcuaro" }, { name: "Sahuayo" }] },
      { name: "Morelos", children: [{ name: "Cuernavaca" }, { name: "Jiutepec" }, { name: "Cuautla" }, { name: "Temixco" }, { name: "Yautepec" }, { name: "Emiliano Zapata" }, { name: "Ayala" }, { name: "Xochitepec" }, { name: "Puente de Ixtla" }, { name: "Jojutla" }] },
      { name: "Nayarit", children: [{ name: "Tepic" }, { name: "Bahía de Banderas" }, { name: "Santiago Ixcuintla" }, { name: "Compostela" }, { name: "Tecuala" }, { name: "Acaponeta" }, { name: "Xalisco" }, { name: "San Blas" }, { name: "Tuxpan" }, { name: "Ixtlán del Río" }] },
      { name: "Nuevo León", children: [{ name: "Monterrey" }, { name: "Apodaca" }, { name: "Guadalupe" }, { name: "General Escobedo" }, { name: "Juárez" }, { name: "San Nicolás de los Garza" }, { name: "García" }, { name: "Santa Catarina" }, { name: "San Pedro Garza García" }, { name: "Cadereyta Jiménez" }, { name: "Santiago" }, { name: "Montemorelos" }, { name: "Linares" }, { name: "Salinas Victoria" }] },
      { name: "Oaxaca", children: [{ name: "Oaxaca de Juárez" }, { name: "San Juan Bautista Tuxtepec" }, { name: "Juchitán de Zaragoza" }, { name: "Santa Cruz Xoxocotlán" }, { name: "Salina Cruz" }, { name: "Heroica Ciudad de Huajuapan de León" }, { name: "Santo Domingo Tehuantepec" }, { name: "San Pedro Mixtepec" }, { name: "Loma Bonita" }, { name: "Santa María Huatulco" }] },
      { name: "Puebla", children: [{ name: "Puebla" }, { name: "Tehuacán" }, { name: "San Martín Texmelucan" }, { name: "Atlixco" }, { name: "San Pedro Cholula" }, { name: "Amozoc" }, { name: "San Andrés Cholula" }, { name: "Huauchinango" }, { name: "Teziutlán" }, { name: "Cuautlancingo" }, { name: "Zacatlán" }, { name: "Izúcar de Matamoros" }] },
      { name: "Querétaro", children: [{ name: "Querétaro" }, { name: "San Juan del Río" }, { name: "El Marqués" }, { name: "Corregidora" }, { name: "Tequisquiapan" }, { name: "Pedro Escobedo" }, { name: "Huimilpan" }, { name: "Colón" }, { name: "Cadereyta de Montes" }, { name: "Ezequiel Montes" }, { name: "Amealco de Bonfil" }] },
      { name: "Quintana Roo", children: [{ name: "Benito Juárez (Cancún)" }, { name: "Solidaridad (Playa del Carmen)" }, { name: "Othón P. Blanco (Chetumal)" }, { name: "Cozumel" }, { name: "Tulum" }, { name: "Felipe Carrillo Puerto" }, { name: "Isla Mujeres" }, { name: "Bacalar" }, { name: "José María Morelos" }, { name: "Puerto Morelos" }, { name: "Lázaro Cárdenas" }] },
      { name: "San Luis Potosí", children: [{ name: "San Luis Potosí" }, { name: "Soledad de Graciano Sánchez" }, { name: "Ciudad Valles" }, { name: "Matehuala" }, { name: "Rioverde" }, { name: "Tamazunchale" }, { name: "Ciudad Fernández" }, { name: "Santa María del Río" }, { name: "Mexquitic de Carmona" }, { name: "Aquismón" }] },
      { name: "Sinaloa", children: [{ name: "Culiacán" }, { name: "Mazatlán" }, { name: "Ahome (Los Mochis)" }, { name: "Guasave" }, { name: "Navolato" }, { name: "Salvador Alvarado (Guamúchil)" }, { name: "El Fuerte" }, { name: "Sinaloa" }, { name: "Rosario" }, { name: "Escuinapa" }] },
      { name: "Sonora", children: [{ name: "Hermosillo" }, { name: "Cajeme (Ciudad Obregón)" }, { name: "Nogales" }, { name: "San Luis Río Colorado" }, { name: "Navojoa" }, { name: "Guaymas" }, { name: "Caborca" }, { name: "Agua Prieta" }, { name: "Huatabampo" }, { name: "Puerto Peñasco" }, { name: "Etchojoa" }, { name: "Empalme" }] },
      { name: "Tabasco", children: [{ name: "Centro (Villahermosa)" }, { name: "Cárdenas" }, { name: "Comalcalco" }, { name: "Huimanguillo" }, { name: "Macuspana" }, { name: "Cunduacán" }, { name: "Nacajuca" }, { name: "Paraíso" }, { name: "Centla" }, { name: "Teapa" }] },
      { name: "Tamaulipas", children: [{ name: "Reynosa" }, { name: "Matamoros" }, { name: "Nuevo Laredo" }, { name: "Ciudad Madero" }, { name: "Tampico" }, { name: "Ciudad Victoria" }, { name: "Altamira" }, { name: "Río Bravo" }, { name: "El Mante" }, { name: "Valle Hermoso" }] },
      { name: "Tlaxcala", children: [{ name: "Tlaxcala" }, { name: "Huamantla" }, { name: "Chiautempan" }, { name: "Apizaco" }, { name: "Zacatelco" }, { name: "San Pablo del Monte" }, { name: "Calpulalpan" }, { name: "Tlaxco" }, { name: "Yauhquemehcan" }, { name: "Contla de Juan Cuamatzi" }] },
      { name: "Veracruz", children: [{ name: "Veracruz" }, { name: "Xalapa" }, { name: "Coatzacoalcos" }, { name: "Córdoba" }, { name: "Poza Rica de Hidalgo" }, { name: "Papantla" }, { name: "Minatitlán" }, { name: "San Andrés Tuxtla" }, { name: "Tuxpan" }, { name: "Boca del Río" }, { name: "Orizaba" }, { name: "Cosoleacaque" }] },
      { name: "Yucatán", children: [{ name: "Mérida" }, { name: "Kanasín" }, { name: "Valladolid" }, { name: "Tizimín" }, { name: "Progreso" }, { name: "Umán" }, { name: "Tekax" }, { name: "Ticul" }, { name: "Chemax" }, { name: "Motul" }, { name: "Oxkutzcab" }] },
      { name: "Zacatecas", children: [{ name: "Zacatecas" }, { name: "Fresnillo" }, { name: "Guadalupe" }, { name: "Jerez" }, { name: "Río Grande" }, { name: "Sombrerete" }, { name: "Loreto" }, { name: "Pinos" }, { name: "Ojocaliente" }, { name: "Calera" }] }
    ]
  },
  {
    country: "ES",
    labelCountry: "España",
    adminType1: "comunidad autónoma",
    adminType2: "municipio",
    children: [
      { name: "Andalucía", children: [{ name: "Sevilla" }, { name: "Málaga" }, { name: "Córdoba" }, { name: "Granada" }, { name: "Jerez de la Frontera" }, { name: "Almería" }, { name: "Huelva" }, { name: "Cádiz" }, { name: "Jaén" }, { name: "Marbella" }, { name: "Dos Hermanas" }] },
      { name: "Aragón", children: [{ name: "Zaragoza" }, { name: "Huesca" }, { name: "Teruel" }, { name: "Calatayud" }] },
      { name: "Asturias", children: [{ name: "Gijón" }, { name: "Oviedo" }, { name: "Avilés" }, { name: "Langreo" }] },
      { name: "Illes Balears", children: [{ name: "Palma de Mallorca" }, { name: "Ibiza" }, { name: "Mahón" }] },
      { name: "Canarias", children: [{ name: "Las Palmas de Gran Canaria" }, { name: "Santa Cruz de Tenerife" }, { name: "San Cristóbal de La Laguna" }] },
      { name: "Cantabria", children: [{ name: "Santander" }, { name: "Torrelavega" }] },
      { name: "Castilla-La Mancha", children: [{ name: "Toledo" }, { name: "Albacete" }, { name: "Guadalajara" }, { name: "Ciudad Real" }, { name: "Cuenca" }] },
      { name: "Castilla y León", children: [{ name: "Valladolid" }, { name: "Burgos" }, { name: "Salamanca" }, { name: "León" }, { name: "Palencia" }, { name: "Zamora" }, { name: "Ávila" }, { name: "Segovia" }, { name: "Soria" }] },
      { name: "Cataluña", children: [{ name: "Barcelona" }, { name: "L'Hospitalet de Llobregat" }, { name: "Terrassa" }, { name: "Badalona" }, { name: "Sabadell" }, { name: "Tarragona" }, { name: "Lleida" }, { name: "Girona" }] },
      { name: "Comunidad Valenciana", children: [{ name: "Valencia" }, { name: "Alicante" }, { name: "Elche" }, { name: "Castellón de la Plana" }, { name: "Torrevieja" }] },
      { name: "Extremadura", children: [{ name: "Badajoz" }, { name: "Cáceres" }, { name: "Mérida" }] },
      { name: "Galicia", children: [{ name: "Vigo" }, { name: "A Coruña" }, { name: "Ourense" }, { name: "Lugo" }, { name: "Santiago de Compostela" }, { name: "Pontevedra" }, { name: "Ferrol" }] },
      { name: "Madrid", children: [{ name: "Madrid" }, { name: "Móstoles" }, { name: "Alcalá de Henares" }, { name: "Fuenlabrada" }, { name: "Leganés" }, { name: "Getafe" }, { name: "Alcorcón" }] },
      { name: "Región de Murcia", children: [{ name: "Murcia" }, { name: "Cartagena" }, { name: "Lorca" }] },
      { name: "Navarra", children: [{ name: "Pamplona" }, { name: "Tudela" }] },
      { name: "La Rioja", children: [{ name: "Logroño" }] },
      { name: "País Vasco", children: [{ name: "Bilbao" }, { name: "Vitoria-Gasteiz" }, { name: "San Sebastián" }, { name: "Barakaldo" }] },
      { name: "Ceuta", children: [{ name: "Ceuta" }] },
      { name: "Melilla", children: [{ name: "Melilla" }] }
    ]
  },
  {
    country: "AR",
    labelCountry: "Argentina",
    adminType1: "provincia",
    adminType2: "ciudad / partido",
    children: [
      { name: "Buenos Aires", children: [{ name: "La Plata" }, { name: "Mar del Plata" }, { name: "Bahía Blanca" }, { name: "Lomas de Zamora" }, { name: "Quilmes" }, { name: "Lanús" }, { name: "Pilar" }, { name: "Tandil" }] },
      { name: "Ciudad Autónoma de Buenos Aires", children: [{ name: "Palermo" }, { name: "Recoleta" }, { name: "Caballito" }, { name: "Belgrano" }, { name: "Villa Urquiza" }, { name: "San Telmo" }] },
      { name: "Catamarca", children: [{ name: "San Fernando del Valle de Catamarca" }] },
      { name: "Chaco", children: [{ name: "Resistencia" }, { name: "Presidencia Roque Sáenz Peña" }] },
      { name: "Chubut", children: [{ name: "Rawson" }, { name: "Comodoro Rivadavia" }, { name: "Trelew" }, { name: "Puerto Madryn" }] },
      { name: "Córdoba", children: [{ name: "Córdoba" }, { name: "Río Cuarto" }, { name: "Villa María" }, { name: "Villa Carlos Paz" }] },
      { name: "Corrientes", children: [{ name: "Corrientes" }, { name: "Goya" }, { name: "Paso de los Libres" }] },
      { name: "Entre Ríos", children: [{ name: "Paraná" }, { name: "Concordia" }, { name: "Gualeguaychú" }] },
      { name: "Formosa", children: [{ name: "Formosa" }] },
      { name: "Jujuy", children: [{ name: "San Salvador de Jujuy" }, { name: "San Pedro de Jujuy" }] },
      { name: "La Pampa", children: [{ name: "Santa Rosa" }, { name: "General Pico" }] },
      { name: "La Rioja", children: [{ name: "La Rioja" }] },
      { name: "Mendoza", children: [{ name: "Mendoza" }, { name: "San Rafael" }, { name: "Godoy Cruz" }, { name: "Guaymallén" }] },
      { name: "Misiones", children: [{ name: "Posadas" }, { name: "Eldorado" }, { name: "Oberá" }] },
      { name: "Neuquén", children: [{ name: "Neuquén" }, { name: "Cutral Có" }, { name: "San Martín de los Andes" }] },
      { name: "Río Negro", children: [{ name: "Viedma" }, { name: "San Carlos de Bariloche" }, { name: "General Roca" }, { name: "Cipolletti" }] },
      { name: "Salta", children: [{ name: "Salta" }, { name: "San Ramón de la Nueva Orán" }, { name: "Tartagal" }] },
      { name: "San Juan", children: [{ name: "San Juan" }, { name: "Chimbas" }] },
      { name: "San Luis", children: [{ name: "San Luis" }, { name: "Villa Mercedes" }] },
      { name: "Santa Cruz", children: [{ name: "Río Gallegos" }, { name: "Caleta Olivia" }] },
      { name: "Santa Fe", children: [{ name: "Santa Fe" }, { name: "Rosario" }, { name: "Rafaela" }, { name: "Venado Tuerto" }] },
      { name: "Santiago del Estero", children: [{ name: "Santiago del Estero" }, { name: "La Banda" }] },
      { name: "Tierra del Fuego", children: [{ name: "Ushuaia" }, { name: "Río Grande" }] },
      { name: "Tucumán", children: [{ name: "San Miguel de Tucumán" }, { name: "Yerba Buena" }, { name: "Tafí Viejo" }] }
    ]
  },
  {
    country: "CO",
    labelCountry: "Colombia",
    adminType1: "departamento",
    adminType2: "municipio",
    children: [
      { name: "Amazonas", children: [{ name: "Leticia" }, { name: "Puerto Nariño" }] },
      { name: "Antioquia", children: [{ name: "Medellín" }, { name: "Bello" }, { name: "Itagüí" }, { name: "Envigado" }, { name: "Rionegro" }, { name: "Apartadó" }, { name: "Turbo" }, { name: "Caucasia" }, { name: "Sabaneta" }, { name: "Caldas" }, { name: "Copacabana" }, { name: "Girardota" }, { name: "La Estrella" }] },
      { name: "Arauca", children: [{ name: "Arauca" }, { name: "Tame" }, { name: "Sarávena" }, { name: "Arauquita" }] },
      { name: "Atlántico", children: [{ name: "Barranquilla" }, { name: "Soledad" }, { name: "Malambo" }, { name: "Puerto Colombia" }, { name: "Sabanalarga" }, { name: "Galapa" }] },
      { name: "Bolívar", children: [{ name: "Cartagena" }, { name: "Magangué" }, { name: "Carmen de Bolívar" }, { name: "Turbaco" }, { name: "Arjona" }, { name: "Santa Rosa" }] },
      { name: "Boyacá", children: [{ name: "Tunja" }, { name: "Duitama" }, { name: "Sogamoso" }, { name: "Chiquinquirá" }, { name: "Puerto Boyacá" }, { name: "Paipa" }] },
      { name: "Caldas", children: [{ name: "Manizales" }, { name: "La Dorada" }, { name: "Chinchiná" }] },
      { name: "Caquetá", children: [{ name: "Florencia" }, { name: "San Vicente del Caguán" }] },
      { name: "Casanare", children: [{ name: "Yopal" }, { name: "Aguazul" }] },
      { name: "Cauca", children: [{ name: "Popayán" }, { name: "Santander de Quilichao" }] },
      { name: "Cesar", children: [{ name: "Valledupar" }, { name: "Aguachica" }] },
      { name: "Chocó", children: [{ name: "Quibdó" }, { name: "Istmina" }] },
      { name: "Córdoba", children: [{ name: "Montería" }, { name: "Cereté" }, { name: "Sahagún" }] },
      { name: "Cundinamarca", children: [{ name: "Bogotá D.C." }, { name: "Soacha" }, { name: "Girardot" }, { name: "Fusagasugá" }, { name: "Zipaquirá" }, { name: "Chía" }, { name: "Facatativá" }] },
      { name: "Guainía", children: [{ name: "Inírida" }] },
      { name: "Guaviare", children: [{ name: "San José del Guaviare" }] },
      { name: "Huila", children: [{ name: "Neiva" }, { name: "Pitalito" }] },
      { name: "La Guajira", children: [{ name: "Riohacha" }, { name: "Maicao" }, { name: "Uribia" }] },
      { name: "Magdalena", children: [{ name: "Santa Marta" }, { name: "Ciénaga" }, { name: "Fundación" }] },
      { name: "Meta", children: [{ name: "Villavicencio" }, { name: "Acacías" }, { name: "Granada" }] },
      { name: "Nariño", children: [{ name: "Pasto" }, { name: "Tumaco" }, { name: "Ipiales" }] },
      { name: "Norte de Santander", children: [{ name: "Cúcuta" }, { name: "Villa del Rosario" }, { name: "Ocaña" }, { name: "Pamplona" }] },
      { name: "Putumayo", children: [{ name: "Mocoa" }, { name: "Puerto Asís" }] },
      { name: "Quindío", children: [{ name: "Armenia" }, { name: "Calarcá" }, { name: "Quimbaya" }] },
      { name: "Risaralda", children: [{ name: "Pereira" }, { name: "Dosquebradas" }, { name: "Santa Rosa de Cabal" }] },
      { name: "San Andrés y Providencia", children: [{ name: "San Andrés" }, { name: "Providencia" }] },
      { name: "Santander", children: [{ name: "Bucaramanga" }, { name: "Floridablanca" }, { name: "Girón" }, { name: "Piedecuesta" }, { name: "Barrancabermeja" }] },
      { name: "Sucre", children: [{ name: "Sincelejo" }, { name: "Corozal" }] },
      { name: "Tolima", children: [{ name: "Ibagué" }, { name: "Espinal" }] },
      { name: "Valle del Cauca", children: [{ name: "Cali" }, { name: "Buenaventura" }, { name: "Palmira" }, { name: "Tuluá" }, { name: "Cartago" }, { name: "Buga" }, { name: "Jamundí" }] },
      { name: "Vaupés", children: [{ name: "Mitú" }] },
      { name: "Vichada", children: [{ name: "Puerto Carreño" }] }
    ]
  },
  {
    country: "VE",
    labelCountry: "Venezuela",
    adminType1: "estado",
    adminType2: "municipio / ciudad",
    children: [
      { name: "Amazonas", children: [{ name: "Atures (Puerto Ayacucho)" }, { name: "Atabapo" }, { name: "Maroa" }, { name: "Río Negro" }] },
      { name: "Anzoátegui", children: [{ name: "Simón Bolívar (Barcelona)" }, { name: "Juan Antonio Sotillo (Puerto La Cruz)" }, { name: "Diego Bautista Urbaneja (Lechería)" }, { name: "Anaco" }, { name: "Simón Rodríguez (El Tigre)" }] },
      { name: "Apure", children: [{ name: "San Fernando" }, { name: "Guasdualito" }, { name: "Achaguas" }, { name: "Biruaca" }] },
      { name: "Aragua", children: [{ name: "Girardot (Maracay)" }, { name: "Santiago Mariño (Turmero)" }, { name: "José Félix Ribas (La Victoria)" }, { name: "Mario Briceño Iragorry (El Limón)" }] },
      { name: "Barinas", children: [{ name: "Barinas" }, { name: "Barinitas" }, { name: "Socopó" }, { name: "Santa Bárbara" }] },
      { name: "Bolívar", children: [{ name: "Caroní (Ciudad Guayana)" }, { name: "Angostura del Orinoco (Ciudad Bolívar)" }, { name: "Piar (Upata)" }, { name: "Sifontes (Tumeremo)" }] },
      { name: "Carabobo", children: [{ name: "Valencia" }, { name: "Puerto Cabello" }, { name: "Naguanagua" }, { name: "San Diego" }, { name: "Guacara" }] },
      { name: "Cojedes", children: [{ name: "Ezequiel Zamora (San Carlos)" }, { name: "Tinaquillo" }] },
      { name: "Delta Amacuro", children: [{ name: "Tucupita" }, { name: "Casacoima" }] },
      { name: "Distrito Capital", children: [{ name: "Libertador (Caracas)" }] },
      { name: "Falcón", children: [{ name: "Miranda (Coro)" }, { name: "Carirubana (Punto Fijo)" }, { name: "Los Taques" }, { name: "Silva (Tucacas)" }] },
      { name: "Guárico", children: [{ name: "Juan Germán Roscio (San Juan de los Morros)" }, { name: "Leonardo Infante (Valle de la Pascua)" }, { name: "Francisco de Miranda (Calabozo)" }] },
      { name: "La Guaira", children: [{ name: "Vargas (La Guaira / Maiquetía / Catia La Mar)" }] },
      { name: "Lara", children: [{ name: "Iribarren (Barquisimeto)" }, { name: "Palavecino (Cabudare)" }, { name: "Torres (Carora)" }, { name: "Jiménez (Quíbor)" }] },
      { name: "Mérida", children: [{ name: "Libertador (Mérida)" }, { name: "Alberto Adriani (El Vigía)" }, { name: "Campo Elías (Ejido)" }] },
      { name: "Miranda", children: [{ name: "Guaicaipuro (Los Teques)" }, { name: "Sucre (Petare / Dos Caminos)" }, { name: "Baruta (El Hatillo)" }, { name: "Chacao" }, { name: "Plaza (Guarenas)" }, { name: "Zamora (Guatire)" }, { name: "Cristóbal Rojas (Charallave)" }] },
      { name: "Monagas", children: [{ name: "Maturín" }, { name: "Ezequiel Zamora (Punta de Mata)" }] },
      {
        name: "Nueva Esparta",
        children: [
          { name: "Maneiro (Pampatar)" },
          { name: "Mariño (Porlamar)" },
          { name: "Arismendi (La Asunción)" },
          { name: "García (El Valle)" },
          { name: "Gómez (Santa Ana)" },
          { name: "Antolín del Campo (Plaza de Paraguachí)" },
          { name: "Marcano (Juan Griego)" },
          { name: "Díaz (San Juan Bautista)" },
          { name: "Tubores (Punta de Piedras)" },
          { name: "Península de Macanao (Boca del Río)" },
          { name: "Villalba (Isla de Coche)" }
        ]
      },
      { name: "Portuguesa", children: [{ name: "Páez (Acarigua)" }, { name: "Guanare" }, { name: "Araure" }] },
      { name: "Sucre", children: [{ name: "Sucre (Cumaná)" }, { name: "Bermúdez (Carúpano)" }] },
      { name: "Táchira", children: [{ name: "San Cristóbal" }, { name: "Cárdenas (Táriba)" }, { name: "Junín (Rubio)" }, { name: "Bolívar (San Antonio)" }] },
      { name: "Trujillo", children: [{ name: "Trujillo" }, { name: "Valera" }, { name: "Boconó" }] },
      { name: "Yaracuy", children: [{ name: "San Felipe" }, { name: "Peña (Yaritagua)" }, { name: "Nirgua" }] },
      { name: "Zulia", children: [{ name: "Maracaibo" }, { name: "San Francisco" }, { name: "Cabimas" }, { name: "Lagunillas (Ciudad Ojeda)" }, { name: "Mara (El Moján)" }, { name: "Colón (Santa Bárbara)" }] }
    ]
  },
  {
    country: "PE",
    labelCountry: "Perú",
    adminType1: "departamento",
    adminType2: "provincia / distrito",
    children: [
      { name: "Amazonas", children: [{ name: "Chachapoyas" }, { name: "Bagua" }, { name: "Utcubamba" }] },
      { name: "Áncash", children: [{ name: "Huaraz" }, { name: "Chimbote" }, { name: "Huari" }] },
      { name: "Apurímac", children: [{ name: "Abancay" }, { name: "Andahuaylas" }] },
      { name: "Arequipa", children: [{ name: "Arequipa City" }, { name: "Caylloma" }, { name: "Camaná" }, { name: "Islay" }] },
      { name: "Ayacucho", children: [{ name: "Huamanga" }, { name: "Huanta" }, { name: "Puquio" }] },
      { name: "Cajamarca", children: [{ name: "Cajamarca" }, { name: "Jaén" }, { name: "Chota" }] },
      { name: "Cusco", children: [{ name: "Cusco City" }, { name: "Urubamba" }, { name: "Canchis" }, { name: "La Convención" }] },
      { name: "Huancavelica", children: [{ name: "Huancavelica" }, { name: "Tayacaja" }] },
      { name: "Huánuco", children: [{ name: "Huánuco" }, { name: "Leoncio Prado" }, { name: "Tingo María" }] },
      { name: "Ica", children: [{ name: "Ica" }, { name: "Chincha" }, { name: "Pisco" }, { name: "Nazca" }] },
      { name: "Junín", children: [{ name: "Huancayo" }, { name: "Chanchamayo" }, { name: "Tarma" }, { name: "Satipo" }] },
      { name: "La Libertad", children: [{ name: "Trujillo" }, { name: "Sánchez Carrión" }, { name: "Pacasmayo" }, { name: "Huamachuco" }] },
      { name: "Lambayeque", children: [{ name: "Chiclayo" }, { name: "Lambayeque City" }, { name: "Ferreñafe" }] },
      { name: "Lima", children: [{ name: "Lima Metropolitana" }, { name: "Callao" }, { name: "Huaura" }, { name: "Cañete" }, { name: "Huaral" }, { name: "Barranca" }] },
      { name: "Loreto", children: [{ name: "Iquitos" }, { name: "Yurimaguas" }, { name: "Nauta" }] },
      { name: "Madre de Dios", children: [{ name: "Puerto Maldonado" }, { name: "Tambopata" }] },
      { name: "Moquegua", children: [{ name: "Moquegua" }, { name: "Ilo" }] },
      { name: "Pasco", children: [{ name: "Cerro de Pasco" }, { name: "Oxapampa" }] },
      { name: "Piura", children: [{ name: "Piura" }, { name: "Sullana" }, { name: "Talara" }, { name: "Paita" }] },
      { name: "Puno", children: [{ name: "Puno" }, { name: "Juliaca" }, { name: "Azángaro" }] },
      { name: "San Martín", children: [{ name: "Moyobamba" }, { name: "Tarapoto" }, { name: "Juanjuí" }] },
      { name: "Tacna", children: [{ name: "Tacna" }, { name: "Jorge Basadre" }] },
      { name: "Tumbes", children: [{ name: "Tumbes" }, { name: "Zarumilla" }] },
      { name: "Ucayali", children: [{ name: "Pucallpa" }, { name: "Coronel Portillo" }] }
    ]
  },
  {
    country: "CL",
    labelCountry: "Chile",
    adminType1: "región",
    adminType2: "comuna",
    children: [
      { name: "Arica y Parinacota", children: [{ name: "Arica" }, { name: "Camarones" }, { name: "Putre" }] },
      { name: "Tarapacá", children: [{ name: "Iquique" }, { name: "Alto Hospicio" }, { name: "Pozo Almonte" }] },
      { name: "Antofagasta", children: [{ name: "Antofagasta" }, { name: "Calama" }, { name: "Tocopilla" }, { name: "Mejillones" }] },
      { name: "Atacama", children: [{ name: "Copiapó" }, { name: "Vallenar" }, { name: "Caldera" }] },
      { name: "Coquimbo", children: [{ name: "La Serena" }, { name: "Coquimbo" }, { name: "Ovalle" }, { name: "Illapel" }] },
      { name: "Valparaíso", children: [{ name: "Valparaíso" }, { name: "Viña del Mar" }, { name: "Quilpué" }, { name: "Villa Alemana" }, { name: "Quillota" }, { name: "San Antonio" }, { name: "Los Andes" }, { name: "San Felipe" }] },
      { name: "Metropolitana de Santiago", children: [{ name: "Santiago" }, { name: "Maipú" }, { name: "Puente Alto" }, { name: "La Florida" }, { name: "Las Condes" }, { name: "Peñalolén" }, { name: "Pudahuel" }, { name: "Quilicura" }, { name: "Ñuñoa" }, { name: "Providencia" }] },
      { name: "O'Higgins", children: [{ name: "Rancagua" }, { name: "San Fernando" }, { name: "Pichilemu" }, { name: "Rengo" }] },
      { name: "Maule", children: [{ name: "Talca" }, { name: "Curicó" }, { name: "Linares" }, { name: "Constitución" }] },
      { name: "Ñuble", children: [{ name: "Chillán" }, { name: "San Carlos" }, { name: "Bulnes" }] },
      { name: "Biobío", children: [{ name: "Concepción" }, { name: "Talcahuano" }, { name: "Los Ángeles" }, { name: "Coronel" }, { name: "Hualpén" }, { name: "Chiguayante" }, { name: "San Pedro de la Paz" }] },
      { name: "La Araucanía", children: [{ name: "Temuco" }, { name: "Padre Las Casas" }, { name: "Angol" }, { name: "Villarrica" }, { name: "Pucón" }] },
      { name: "Los Ríos", children: [{ name: "Valdivia" }, { name: "La Unión" }, { name: "Río Bueno" }] },
      { name: "Los Lagos", children: [{ name: "Puerto Montt" }, { name: "Osorno" }, { name: "Castro" }, { name: "Puerto Varas" }, { name: "Ancud" }] },
      { name: "Aysén", children: [{ name: "Coyhaique" }, { name: "Puerto Aysén" }] },
      { name: "Magallanes", children: [{ name: "Punta Arenas" }, { name: "Puerto Natales" }] }
    ]
  },
  {
    country: "EC",
    labelCountry: "Ecuador",
    adminType1: "provincia",
    adminType2: "cantón",
    children: [
      { name: "Azuay", children: [{ name: "Cuenca" }, { name: "Gualaceo" }, { name: "Paute" }] },
      { name: "Bolívar", children: [{ name: "Guaranda" }] },
      { name: "Cañar", children: [{ name: "Azogues" }, { name: "La Troncal" }] },
      { name: "Carchi", children: [{ name: "Tulcán" }] },
      { name: "Chimborazo", children: [{ name: "Riobamba" }] },
      { name: "Cotopaxi", children: [{ name: "Latacunga" }] },
      { name: "El Oro", children: [{ name: "Machala" }, { name: "Pasaje" }, { name: "Santa Rosa" }] },
      { name: "Esmeraldas", children: [{ name: "Esmeraldas" }, { name: "Atacames" }, { name: "Quinindé" }] },
      { name: "Galápagos", children: [{ name: "Puerto Ayora" }, { name: "Puerto Baquerizo Moreno" }] },
      { name: "Guayas", children: [{ name: "Guayaquil" }, { name: "Durán" }, { name: "Samborondón" }, { name: "Daule" }, { name: "Milagro" }, { name: "Playas" }] },
      { name: "Imbabura", children: [{ name: "Ibarra" }, { name: "Otavalo" }, { name: "Cotacachi" }] },
      { name: "Loja", children: [{ name: "Loja" }, { name: "Catamayo" }] },
      { name: "Los Ríos", children: [{ name: "Babahoyo" }, { name: "Quevedo" }] },
      { name: "Manabí", children: [{ name: "Portoviejo" }, { name: "Manta" }, { name: "Chone" }, { name: "Montecristi" }] },
      { name: "Morona Santiago", children: [{ name: "Macas" }] },
      { name: "Napo", children: [{ name: "Tena" }] },
      { name: "Orellana", children: [{ name: "Puerto Francisco de Orellana (Coca)" }] },
      { name: "Pastaza", children: [{ name: "Puyo" }] },
      { name: "Pichincha", children: [{ name: "Quito D.M." }, { name: "Sangolquí" }, { name: "Cayambe" }, { name: "Machachi" }] },
      { name: "Santa Elena", children: [{ name: "Santa Elena City" }, { name: "Salinas" }, { name: "La Libertad" }] },
      { name: "Santo Domingo de los Tsáchilas", children: [{ name: "Santo Domingo" }] },
      { name: "Sucumbíos", children: [{ name: "Nueva Loja (Lago Agrio)" }] },
      { name: "Tungurahua", children: [{ name: "Ambato" }, { name: "Baños" }] },
      { name: "Zamora Chinchipe", children: [{ name: "Zamora" }] }
    ]
  },
  {
    country: "BO",
    labelCountry: "Bolivia",
    adminType1: "departamento",
    adminType2: "municipio",
    children: [
      { name: "Beni", children: [{ name: "Trinidad" }, { name: "Riberalta" }, { name: "Guayaramerín" }] },
      { name: "Chuquisaca", children: [{ name: "Sucre" }] },
      { name: "Cochabamba", children: [{ name: "Cochabamba" }, { name: "Quillacollo" }, { name: "Sacaba" }] },
      { name: "La Paz", children: [{ name: "La Paz City" }, { name: "El Alto" }, { name: "Viacha" }] },
      { name: "Oruro", children: [{ name: "Oruro" }] },
      { name: "Pando", children: [{ name: "Cobija" }] },
      { name: "Potosí", children: [{ name: "Potosí" }, { name: "Uyuni" }] },
      { name: "Santa Cruz", children: [{ name: "Santa Cruz de la Sierra" }, { name: "Montero" }, { name: "Warnes" }, { name: "La Guardia" }] },
      { name: "Tarija", children: [{ name: "Tarija" }, { name: "Yacuiba" }, { name: "Bermejo" }] }
    ]
  },
  {
    country: "UY",
    labelCountry: "Uruguay",
    adminType1: "departamento",
    adminType2: "municipio / zona",
    children: [
      { name: "Artigas", children: [{ name: "Artigas" }, { name: "Bella Unión" }] },
      { name: "Canelones", children: [{ name: "Canelones" }, { name: "Las Piedras" }, { name: "Pando" }, { name: "Ciudad de la Costa" }] },
      { name: "Cerro Largo", children: [{ name: "Melo" }] },
      { name: "Colonia", children: [{ name: "Colonia del Sacramento" }, { name: "Carmelo" }] },
      { name: "Durazno", children: [{ name: "Durazno" }] },
      { name: "Flores", children: [{ name: "Trinidad" }] },
      { name: "Florida", children: [{ name: "Florida" }] },
      { name: "Lavalleja", children: [{ name: "Minas" }] },
      { name: "Maldonado", children: [{ name: "Maldonado" }, { name: "Punta del Este" }, { name: "San Carlos" }] },
      { name: "Montevideo", children: [{ name: "Montevideo" }, { name: "Pocitos" }, { name: "Carrasco" }, { name: "Centro" }, { name: "Cordón" }] },
      { name: "Paysandú", children: [{ name: "Paysandú" }] },
      { name: "Río Negro", children: [{ name: "Fray Bentos" }] },
      { name: "Rivera", children: [{ name: "Rivera" }] },
      { name: "Rocha", children: [{ name: "Rocha" }, { name: "Chuy" }] },
      { name: "Salto", children: [{ name: "Salto" }] },
      { name: "San José", children: [{ name: "San José de Mayo" }, { name: "Ciudad del Plata" }] },
      { name: "Soriano", children: [{ name: "Mercedes" }] },
      { name: "Tacuarembó", children: [{ name: "Tacuarembó" }, { name: "Paso de los Toros" }] },
      { name: "Treinta y Tres", children: [{ name: "Treinta y Tres" }] }
    ]
  },
  {
    country: "PY",
    labelCountry: "Paraguay",
    adminType1: "departamento",
    adminType2: "distrito",
    children: [
      { name: "Alto Paraguay", children: [{ name: "Fuerte Olimpo" }] },
      { name: "Alto Paraná", children: [{ name: "Ciudad del Este" }, { name: "Hernandarias" }, { name: "Presidente Franco" }] },
      { name: "Amambay", children: [{ name: "Pedro Juan Caballero" }] },
      { name: "Asunción", children: [{ name: "Asunción" }] },
      { name: "Boquerón", children: [{ name: "Filadelfia" }] },
      { name: "Caaguazú", children: [{ name: "Coronel Oviedo" }, { name: "Caaguazú" }] },
      { name: "Caazapá", children: [{ name: "Caazapá" }] },
      { name: "Canindeyú", children: [{ name: "Salto del Guairá" }] },
      { name: "Central", children: [{ name: "Luque" }, { name: "San Lorenzo" }, { name: "Lambaré" }, { name: "Fernando de la Mora" }, { name: "Capiatá" }] },
      { name: "Concepción", children: [{ name: "Concepción" }] },
      { name: "Cordillera", children: [{ name: "Caacupé" }] },
      { name: "Guairá", children: [{ name: "Villarrica" }] },
      { name: "Itapúa", children: [{ name: "Encarnación" }] },
      { name: "Misiones", children: [{ name: "San Juan Bautista" }] },
      { name: "Ñeembucú", children: [{ name: "Pilar" }] },
      { name: "Paraguarí", children: [{ name: "Paraguarí" }] },
      { name: "Presidente Hayes", children: [{ name: "Villa Hayes" }] },
      { name: "San Pedro", children: [{ name: "San Pedro de Ycuamandiyú" }] }
    ]
  },
  {
    country: "PA",
    labelCountry: "Panamá",
    adminType1: "provincia",
    adminType2: "distrito",
    children: [
      { name: "Bocas del Toro", children: [{ name: "Bocas del Toro City" }, { name: "Changuinola" }] },
      { name: "Chiriquí", children: [{ name: "David" }, { name: "Boquete" }, { name: "Bugaba" }, { name: "Barú" }] },
      { name: "Coclé", children: [{ name: "Penonomé" }, { name: "Aguadulce" }, { name: "Antón" }] },
      { name: "Colón", children: [{ name: "Colón City" }] },
      { name: "Darién", children: [{ name: "La Palma" }] },
      { name: "Herrera", children: [{ name: "Chitré" }] },
      { name: "Los Santos", children: [{ name: "Las Tablas" }] },
      { name: "Panamá", children: [{ name: "Ciudad de Panamá" }, { name: "San Miguelito" }] },
      { name: "Panamá Oeste", children: [{ name: "La Chorrera" }, { name: "Arraiján" }, { name: "Chame" }] },
      { name: "Veraguas", children: [{ name: "Santiago" }] },
      { name: "Comarca Guna Yala", children: [{ name: "El Porvenir" }] },
      { name: "Comarca Ngäbe-Buglé", children: [{ name: "Chichica" }] },
      { name: "Comarca Emberá-Wounaan", children: [{ name: "Unión Chocó" }] }
    ]
  },
  {
    country: "CR",
    labelCountry: "Costa Rica",
    adminType1: "provincia",
    adminType2: "cantón",
    children: [
      { name: "Alajuela", children: [{ name: "Alajuela" }, { name: "San Carlos" }] },
      { name: "Cartago", children: [{ name: "Cartago" }, { name: "La Unión" }] },
      { name: "Guanacaste", children: [{ name: "Liberia" }, { name: "Nicoya" }] },
      { name: "Heredia", children: [{ name: "Heredia" }, { name: "San Pablo" }] },
      { name: "Limón", children: [{ name: "Limón" }, { name: "Pococí" }] },
      { name: "Puntarenas", children: [{ name: "Puntarenas" }, { name: "Esparza" }] },
      { name: "San José", children: [{ name: "San José City" }, { name: "Escazú" }, { name: "Desamparados" }, { name: "Santa Ana" }] }
    ]
  },
  {
    country: "NI",
    labelCountry: "Nicaragua",
    adminType1: "departamento",
    adminType2: "municipio",
    children: [
      { name: "Boaco", children: [{ name: "Boaco" }] },
      { name: "Carazo", children: [{ name: "Jinotepe" }, { name: "Diriamba" }] },
      { name: "Chinandega", children: [{ name: "Chinandega" }, { name: "Corinto" }] },
      { name: "Chontales", children: [{ name: "Juigalpa" }] },
      { name: "Estelí", children: [{ name: "Estelí" }] },
      { name: "Granada", children: [{ name: "Granada" }] },
      { name: "Jinotega", children: [{ name: "Jinotega" }] },
      { name: "León", children: [{ name: "León" }] },
      { name: "Madriz", children: [{ name: "Somoto" }] },
      { name: "Managua", children: [{ name: "Managua City" }, { name: "Tipitapa" }, { name: "Ciudad Sandino" }] },
      { name: "Masaya", children: [{ name: "Masaya" }] },
      { name: "Matagalpa", children: [{ name: "Matagalpa" }] },
      { name: "Nueva Segovia", children: [{ name: "Ocotal" }] },
      { name: "Río San Juan", children: [{ name: "San Carlos" }] },
      { name: "Rivas", children: [{ name: "Rivas" }, { name: "San Juan del Sur" }] },
      { name: "RACCN", children: [{ name: "Puerto Cabezas" }, { name: "Waspán" }] },
      { name: "RACCS", children: [{ name: "Bluefields" }] }
    ]
  },
  {
    country: "HN",
    labelCountry: "Honduras",
    adminType1: "departamento",
    adminType2: "municipio",
    children: [
      { name: "Atlántida", children: [{ name: "La Ceiba" }, { name: "Tela" }] },
      { name: "Choluteca", children: [{ name: "Choluteca" }] },
      { name: "Colón", children: [{ name: "Trujillo" }, { name: "Tocoa" }] },
      { name: "Comayagua", children: [{ name: "Comayagua" }, { name: "Siguatepeque" }] },
      { name: "Copán", children: [{ name: "Santa Rosa de Copán" }] },
      { name: "Cortés", children: [{ name: "San Pedro Sula" }, { name: "Puerto Cortés" }, { name: "Choloma" }, { name: "Villanueva" }, { name: "La Lima" }] },
      { name: "El Paraíso", children: [{ name: "Yuscarán" }, { name: "Danlí" }] },
      { name: "Francisco Morazán", children: [{ name: "Tegucigalpa" }, { name: "Comayagüela" }] },
      { name: "Gracias a Dios", children: [{ name: "Puerto Lempira" }] },
      { name: "Intibucá", children: [{ name: "La Esperanza" }] },
      { name: "Islas de la Bahía", children: [{ name: "Roatán" }, { name: "Utila" }] },
      { name: "La Paz", children: [{ name: "La Paz" }] },
      { name: "Lempira", children: [{ name: "Gracias" }] },
      { name: "Ocotepeque", children: [{ name: "Nueva Ocotepeque" }] },
      { name: "Olancho", children: [{ name: "Juticalpa" }, { name: "Catacamas" }] },
      { name: "Santa Bárbara", children: [{ name: "Santa Bárbara" }] },
      { name: "Valle", children: [{ name: "Nacaome" }] },
      { name: "Yoro", children: [{ name: "Yoro" }, { name: "El Progreso" }, { name: "Olanchito" }] }
    ]
  },
  {
    country: "SV",
    labelCountry: "El Salvador",
    adminType1: "departamento",
    adminType2: "municipio",
    children: [
      { name: "Ahuachapán", children: [{ name: "Ahuachapán" }] },
      { name: "Cabañas", children: [{ name: "Sensuntepeque" }] },
      { name: "Chalatenango", children: [{ name: "Chalatenango" }] },
      { name: "Cuscatlán", children: [{ name: "Cojutepeque" }] },
      { name: "La Libertad", children: [{ name: "Santa Tecla" }] },
      { name: "La Paz", children: [{ name: "Zacatecoluca" }] },
      { name: "La Unión", children: [{ name: "La Unión" }] },
      { name: "Morazán", children: [{ name: "San Francisco Gotera" }] },
      { name: "San Miguel", children: [{ name: "San Miguel" }] },
      { name: "San Salvador", children: [{ name: "San Salvador City" }, { name: "Soyapango" }] },
      { name: "San Vicente", children: [{ name: "San Vicente" }] },
      { name: "Santa Ana", children: [{ name: "Santa Ana" }] },
      { name: "Sonsonate", children: [{ name: "Sonsonate" }] },
      { name: "Usulután", children: [{ name: "Usulután" }] }
    ]
  },
  {
    country: "GT",
    labelCountry: "Guatemala",
    adminType1: "departamento",
    adminType2: "municipio",
    children: [
      { name: "Alta Verapaz", children: [{ name: "Cobán" }] },
      { name: "Baja Verapaz", children: [{ name: "Salamá" }] },
      { name: "Chimaltenango", children: [{ name: "Chimaltenango" }] },
      { name: "Chiquimula", children: [{ name: "Chiquimula" }] },
      { name: "El Progreso", children: [{ name: "Guastatoya" }] },
      { name: "Escuintla", children: [{ name: "Escuintla" }] },
      { name: "Guatemala", children: [{ name: "Ciudad de Guatemala" }, { name: "Mixco" }, { name: "Villa Nueva" }] },
      { name: "Huehuetenango", children: [{ name: "Huehuetenango" }] },
      { name: "Izabal", children: [{ name: "Puerto Barrios" }] },
      { name: "Jalapa", children: [{ name: "Jalapa" }] },
      { name: "Jutiapa", children: [{ name: "Jutiapa" }] },
      { name: "Petén", children: [{ name: "Flores" }] },
      { name: "Quetzaltenango", children: [{ name: "Quetzaltenango" }] },
      { name: "Quiché", children: [{ name: "Santa Cruz del Quiché" }] },
      { name: "Retalhuleu", children: [{ name: "Retalhuleu" }] },
      { name: "Sacatepéquez", children: [{ name: "Antigua Guatemala" }] },
      { name: "San Marcos", children: [{ name: "San Marcos" }] },
      { name: "Santa Rosa", children: [{ name: "Cuilapa" }] },
      { name: "Sololá", children: [{ name: "Sololá" }] },
      { name: "Suchitepéquez", children: [{ name: "Mazatenango" }] },
      { name: "Totonicapán", children: [{ name: "Totonicapán" }] },
      { name: "Zacapa", children: [{ name: "Zacapa" }] }
    ]
  },
  {
    country: "CU",
    labelCountry: "Cuba",
    adminType1: "provincia",
    adminType2: "municipio",
    children: [
      { name: "Artemisa", children: [{ name: "Artemisa" }] },
      { name: "Camagüey", children: [{ name: "Camagüey" }] },
      { name: "Ciego de Ávila", children: [{ name: "Ciego de Ávila" }] },
      { name: "Cienfuegos", children: [{ name: "Cienfuegos" }] },
      { name: "Granma", children: [{ name: "Bayamo" }, { name: "Manzanillo" }] },
      { name: "Guantánamo", children: [{ name: "Guantánamo" }] },
      { name: "Holguín", children: [{ name: "Holguín" }] },
      { name: "Isla de la Juventud", children: [{ name: "Nueva Gerona" }] },
      { name: "La Habana", children: [{ name: "La Habana City" }, { name: "Centro Habana" }, { name: "Plaza de la Revolución" }, { name: "Habana del Este" }] },
      { name: "Las Tunas", children: [{ name: "Las Tunas" }] },
      { name: "Matanzas", children: [{ name: "Matanzas" }, { name: "Varadero" }] },
      { name: "Mayabeque", children: [{ name: "San José de las Lajas" }] },
      { name: "Pinar del Río", children: [{ name: "Pinar del Río" }] },
      { name: "Sancti Spíritus", children: [{ name: "Sancti Spíritus" }, { name: "Trinidad" }] },
      { name: "Santiago de Cuba", children: [{ name: "Santiago de Cuba" }] },
      { name: "Villa Clara", children: [{ name: "Santa Clara" }] }
    ]
  },
  {
    country: "DO",
    labelCountry: "República Dominicana",
    adminType1: "provincia",
    adminType2: "municipio",
    children: [
      { name: "Azua", children: [{ name: "Azua de Compostela" }, { name: "Las Charcas" }, { name: "Estebanía" }, { name: "Padre Las Casas" }, { name: "Peralta" }, { name: "Sabana Yegua" }] },
      { name: "Baoruco", children: [{ name: "Neiba" }, { name: "Galván" }, { name: "Los Ríos" }, { name: "Tamayo" }, { name: "Villa Jaragua" }] },
      { name: "Barahona", children: [{ name: "Santa Cruz de Barahona" }, { name: "Cabral" }, { name: "Enriquillo" }, { name: "Paraíso" }, { name: "Vicente Noble" }] },
      { name: "Dajabón", children: [{ name: "Dajabón" }, { name: "Loma de Cabrera" }, { name: "Restauración" }, { name: "Partido" }] },
      { name: "Distrito Nacional", children: [{ name: "Santo Domingo de Guzmán" }, { name: "Piantini" }, { name: "Naco" }, { name: "Gazcue" }, { name: "Bella Vista" }] },
      { name: "Duarte", children: [{ name: "San Francisco de Macorís" }, { name: "Arenoso" }, { name: "Castillo" }, { name: "Pimentel" }, { name: "Villa Riva" }] },
      { name: "El Seibo", children: [{ name: "Santa Cruz de El Seibo" }, { name: "Miches" }] },
      { name: "Elías Piña", children: [{ name: "Comendador" }, { name: "Bánica" }, { name: "Hondo Valle" }, { name: "Juan Santiago" }] },
      { name: "Espaillat", children: [{ name: "Moca" }, { name: "Cayetano Germosén" }, { name: "Gaspar Hernández" }, { name: "Jamao al Norte" }] },
      { name: "Hato Mayor", children: [{ name: "Hato Mayor del Rey" }, { name: "El Valle" }, { name: "Sabana de la Mar" }] },
      { name: "Hermanas Mirabal", children: [{ name: "Salcedo" }, { name: "Tenares" }, { name: "Villa Tapia" }] },
      { name: "Independencia", children: [{ name: "Jimaní" }, { name: "Duvergé" }, { name: "La Descubierta" }, { name: "Mella" }, { name: "Postrer Río" }] },
      { name: "La Altagracia", children: [{ name: "Higüey" }, { name: "Bávaro" }, { name: "Punta Cana" }, { name: "Verón" }, { name: "San Rafael del Yuma" }, { name: "Bayahibe" }] },
      { name: "La Romana", children: [{ name: "La Romana" }, { name: "Guaymate" }, { name: "Villa Hermosa" }] },
      { name: "La Vega", children: [{ name: "Concepción de La Vega" }, { name: "Jarabacoa" }, { name: "Constanza" }, { name: "Jima Abajo" }] },
      { name: "María Trinidad Sánchez", children: [{ name: "Nagua" }, { name: "Cabrera" }, { name: "El Factor" }, { name: "Río San Juan" }] },
      { name: "Monseñor Nouel", children: [{ name: "Bonao" }, { name: "Maimón" }, { name: "Piedra Blanca" }] },
      { name: "Monte Cristi", children: [{ name: "San Fernando de Monte Cristi" }, { name: "Castañuelas" }, { name: "Guayubín" }, { name: "Las Matas de Santa Cruz" }, { name: "Pepillo Salcedo" }, { name: "Villa Vásquez" }] },
      { name: "Monte Plata", children: [{ name: "Monte Plata" }, { name: "Bayaguana" }, { name: "Peralvillo" }, { name: "Sabana Grande de Boyá" }, { name: "Yamasá" }] },
      { name: "Pedernales", children: [{ name: "Pedernales" }, { name: "Oviedo" }] },
      { name: "Peravia", children: [{ name: "Baní" }, { name: "Matanzas" }, { name: "Nizao" }] },
      { name: "Puerto Plata", children: [{ name: "San Felipe de Puerto Plata" }, { name: "Altamira" }, { name: "Imbert" }, { name: "Luperón" }, { name: "Sosúa" }, { name: "Cabarete" }, { name: "Villa Montellano" }] },
      { name: "Samaná", children: [{ name: "Santa Bárbara de Samaná" }, { name: "Las Terrenas" }, { name: "Sánchez" }] },
      { name: "San Cristóbal", children: [{ name: "San Cristóbal" }, { name: "Bajos de Haina" }, { name: "San Gregorio de Nigua" }, { name: "Villa Altagracia" }, { name: "Yaguate" }, { name: "Palenque" }] },
      { name: "San José de Ocoa", children: [{ name: " San José de Ocoa" }, { name: "Rancho Arriba" }, { name: "Sabana Larga" }] },
      { name: "San Juan", children: [{ name: "San Juan de la Maguana" }, { name: "Bohechío" }, { name: "El Cercado" }, { name: "Las Matas de Farfán" }, { name: "Vallejuelo" }] },
      { name: "San Pedro de Macorís", children: [{ name: "San Pedro de Macorís" }, { name: "Consuelo" }, { name: "Quisqueya" }, { name: "Ramón Santana" }, { name: "San José de Los Llanos" }] },
      { name: "Sánchez Ramírez", children: [{ name: "Cotuí" }, { name: "Cevicos" }, { name: "Fantino" }, { name: "Villa La Mata" }] },
      { name: "Santiago", children: [{ name: "Santiago de los Caballeros" }, { name: "Bisonó (Navarrete)" }, { name: "Jánico" }, { name: "Licey al Medio" }, { name: "Puñal" }, { name: "San José de las Matas" }, { name: "Tamboril" }, { name: "Villa González" }] },
      { name: "Santiago Rodríguez", children: [{ name: "Sabaneta" }, { name: "Monción" }, { name: "Villa Los Almácigos" }] },
      { name: "Santo Domingo", children: [{ name: "Santo Domingo Este" }, { name: "Santo Domingo Oeste" }, { name: "Santo Domingo Norte" }, { name: "Boca Chica" }, { name: "Los Alcarrizos" }, { name: "Pedro Brand" }, { name: "San Antonio de Guerra" }] },
      { name: "Valverde", children: [{ name: "Mao" }, { name: "Esperanza" }, { name: "Laguna Salada" }] }
    ]
  },
  {
    country: "PR",
    labelCountry: "Puerto Rico",
    adminType1: "municipio",
    adminType2: "barrio / zona",
    children: [
      { name: "San Juan", children: [{ name: "Condado" }, { name: "Santurce" }, { name: "Viejo San Juan" }, { name: "Hato Rey" }, { name: "Río Piedras" }] },
      { name: "Bayamón", children: [{ name: "Hato Tejas" }, { name: "Pájaros" }, { name: "Minillas" }] },
      { name: "Carolina", children: [{ name: "Isla Verde" }, { name: "Sabana Abajo" }, { name: "Trujillo Bajo" }] },
      { name: "Ponce", children: [{ name: "Playa" }, { name: "Canas" }, { name: "Machuelo" }] },
      { name: "Caguas", children: [{ name: "Bairoa" }, { name: "Cañabón" }] },
      { name: "Guaynabo", children: [{ name: "Frailes" }, { name: "Guaynabo Pueblo" }] },
      { name: "Mayagüez", children: [{ name: "Mayagüez Pueblo" }, { name: "Sabanalos" }] },
      { name: "Trujillo Alto", children: [{ name: "Cuevas" }, { name: "Carraízo" }] },
      { name: "Arecibo", children: [{ name: "Santana" }, { name: "Arecibo Pueblo" }] },
      { name: "Fajardo", children: [{ name: "Fajardo Pueblo" }, { name: "Cabezas" }] }
    ]
  },
  {
    country: "GQ",
    labelCountry: "Guinea Ecuatorial",
    adminType1: "provincia",
    adminType2: "distrito",
    children: [
      { name: "Annobón", children: [{ name: "San Antonio de Palé" }] },
      { name: "Bioko Norte", children: [{ name: "Malabo" }, { name: "Rebola" }] },
      { name: "Bioko Sur", children: [{ name: "Luba" }] },
      { name: "Centro Sur", children: [{ name: "Evinayong" }] },
      { name: "Kié-Ntem", children: [{ name: "Ebebiyín" }] },
      { name: "Litoral", children: [{ name: "Bata" }] },
      { name: "Wele-Nzas", children: [{ name: "Mongomo" }] }
    ]
  }
];
