
export const MAP_CATEGORIES = [
  { id: "todas", label: "Todos", match: "", color: "#00FFFF", emoji: "📍" },
  {
    id: "hogar",
    label: "🛠️ Hogar",
    match: "Reparaciones y Mantenimiento del Hogar",
    color: "#3399FF",
    emoji: "🛠️",
  },
  {
    id: "bienestar",
    label: "⚕️ Salud",
    match: "Salud y Cuidados Médicos",
    color: "#FF3333",
    emoji: "⚕️",
  },
  {
    id: "belleza",
    label: "💇‍♀️ Estética",
    match: "Estética y Cuidado Personal",
    color: "#FF00FF",
    emoji: "💇‍♀️",
  },
  {
    id: "tecnologia",
    label: "💻 Tecnología",
    match: "Tecnología y Soporte Digital",
    color: "#B026FF",
    emoji: "💻",
  },
  {
    id: "vehiculos",
    label: "🚗 Vehículos",
    match: "Vehículos y Transporte",
    color: "#FF6600",
    emoji: "🚗",
  },
  {
    id: "eventos",
    label: "🎉 Eventos",
    match: "Eventos y Producción",
    color: "#FFD700",
    emoji: "🎉",
  },
  {
    id: "educacion",
    label: "📚 Educación",
    match: "Educación y Asesoría",
    color: "#00FFCC",
    emoji: "📚",
  },
  {
    id: "gestoria",
    label: "💼 Gestoría",
    match: "Servicios y Gestoria",
    color: "#A0AEC0",
    emoji: "💼",
  },
  {
    id: "limpieza",
    label: "🧹 Limpieza",
    match: "Servicios Generales y Mandados",
    color: "#33FF33",
    emoji: "🧹",
  },
  {
    id: "mascotas",
    label: "🐾 Mascotas",
    match: "Mascotas",
    color: "#D2691E",
    emoji: "🐾",
  },
];

export const SERVICE_CATEGORIES = [
  {
    title: "Reparaciones y Mantenimiento del Hogar",
    icon: "🛠️",
    description: "Las urgencias son el principal motor de búsqueda en esta categoría.",
    services: [
      "Plomero / Fontanero",
      "Electricista",
      "Técnico de Aires Acondicionados y Refrigeración",
      "Cerrajero (Servicio 24 horas)",
      "Reparador de Electrodomésticos (Neveras, Lavadoras)",
      "Fumigador / Control de plagas",
      "Albañil",
      "Pintor",
      "Carpintero",
      "Herrero / Soldador",
      "Impermeabilizador de techos",
      "Instalador de Gas",
      "Mantenimiento y limpieza de tanques/piscinas",
      "Vidriero",
      "Técnico de Bombas de Agua",
    ],
  },
  {
    title: "Salud y Cuidados Médicos",
    icon: "⚕️",
    services: [
      "Médico General (Consultas a domicilio)",
      "Enfermero(a)",
      "Fisioterapeuta / Rehabilitador",
      "Odontólogo / Emergencias dentales",
      "Psicólogo",
      "Nutricionista",
      "Pediatra",
      "Ginecólogo",
      "Cuidador de Adultos Mayores",
      "Entrenador Personal",
      "Optometrista",
      "Medicina holística",
      "Médico General",
      "Quiropráctico",
      "Servicio de Paramédicos / Ambulancia",
    ],
  },
  {
    title: "Estética y Cuidado Personal",
    icon: "💇‍♀️",
    services: [
      "Peluquero / Estilista",
      "Barbero",
      "Manicurista / Pedicurista",
      "Maquillador Profesional",
      "Especialista en Cejas y Pestañas (Lashista)",
      "Especialista en Depilación",
      "Tatuador",
      "Cosmetólogo / Limpiezas faciales",
      "Masajista Relajante / Estético",
      "Asesor de Imagen",
    ],
  },
  {
    title: "Tecnología y Soporte Digital",
    icon: "💻",
    services: [
      "Técnico de Celulares y Tablets",
      "Técnico de Computadoras",
      "Instalador de Cámaras de Seguridad (CCTV)",
      "Instalador de Redes y Antenas de Internet",
      "Desarrollador Web / App",
      "Diseñador Gráfico",
      "Gestor de Redes Sociales (Community Manager)",
      "Especialista en Marketing Digital",
      "Reparador de Consolas de Videojuegos",
      "Técnico de Impresoras",
    ],
  },
  {
    title: "Vehículos y Transporte",
    icon: "🚗",
    services: [
      "Mecánico Automotriz",
      "Mecánico de Motos",
      "Servicio de Grúa",
      "Latonero y Pintor",
      "Cauchero / Vulcanizador (Reparación de neumáticos)",
      "Especialista en Frenos",
      "Instalador de Alarmas, Sonido y GPS",
      "Servicio de Fletes y Mudanzas",
      "Chofer Privado / Servicio de Taxi",
      "Moto Taxi",
      "Delivery / Mensajería",
      "Limpiador de Tapicería Automotriz",
    ],
  },
  {
    title: "Eventos y Producción",
    icon: "🎉",
    services: [
      "Fotógrafo",
      "Videógrafo",
      "DJ Profesional",
      "Organizador de Eventos (Wedding/Event Planner)",
      "Animador / Presentador",
      "Mesero / Personal de Protocolo",
      "Chef Privado / Servicio de Catering",
      "Decorador de Fiestas",
      "Músico / Banda en vivo",
      "Bartender / Mixólogo",
    ],
  },
  {
    title: "Educación y Asesoría",
    icon: "📚",
    description: "Esta categoría es el motor de conocimiento de la plataforma, alineada con tu visión de formación tecnológica.",
    services: [
      "Mentor / Asesor de Startups",
      "Marketing Digital / Influencer",
      "Profesor de Programación / IA",
      "Gestor de Trámites / Tramitador",
      "Profesor de Idiomas (Especialmente Inglés)",
      "Tutor Académico (Matemáticas, Física)",
      "Instructor de Manejo",
      "Profesor de Música (Instrumentos, Canto)",
      "Instructor de Yoga / Pilates",
      "Entrenador de Deportes",
      "Tutor de Computación / Software",
      "Traductor Profesional",
    ],
  },
  {
    title: "Servicios y Gestoria",
    icon: "💼",
    services: [
      "Abogado (Laboral, Penal, Civil)",
      "Contador Público",
      "Asesor Inmobiliario (Corredor)",
      "Gestor de Trámites y Documentos",
      "Arquitecto",
      "Topógrafo",
      "Asesor de Seguros",
      "Redactor / Corrector de Documentos",
      "Gestor de Aduanas",
      "Tasador / Perito",
    ],
  },
  {
    title: "Servicios Generales y Mandados",
    icon: "🧹",
    description: "La categoría de mayor rotación y uso diario dentro de la PWA.",
    services: [
      "Limpieza por Horas (Personal de Servicio)",
      "Concierge / Asistente de Compras",
      "Gruista / Asistencia Vial",
      "Lavandería y Tintorería a Domicilio",
      "Jardinero / Paisajista",
      "Niñera (Babysitter)",
      "Costurera / Sastre",
    ],
  },
  {
    title: "Mascotas",
    icon: "🐾",
    description: "Un sector de alta fidelidad que requiere confianza y geolocalización precisa.",
    services: [
      "Transporte de Mascotas (Pet Taxi)",
      "Adiestrador Canino / Etólogo",
      "Hotel Canino / Guardería de Mascotas",
      "Funeraria / Cremación de Mascotas",
      "Veterinario (Clínica y Domicilio)",
      "Peluquero Canino / Felino",
      "Paseador de Perros",
    ],
  },
];
